# Generated by Django 5.2.4 on 2025-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('luke', models.IntegerField()),
                ('jamie', models.IntegerField()),
                ('manon', models.IntegerField()),
                ('kimberly', models.IntegerField()),
                ('marisa', models.IntegerField()),
                ('lily', models.IntegerField()),
                ('jp', models.IntegerField()),
                ('juri', models.IntegerField()),
                ('deejay', models.IntegerField()),
                ('cammy', models.IntegerField()),
                ('ryu', models.IntegerField()),
                ('ehonda', models.IntegerField()),
                ('blanka', models.IntegerField()),
                ('guile', models.IntegerField()),
                ('ken', models.IntegerField()),
                ('chunli', models.IntegerField()),
                ('zangief', models.IntegerField()),
                ('dhalsim', models.IntegerField()),
                ('rashid', models.IntegerField()),
                ('aki', models.IntegerField()),
                ('ed', models.IntegerField()),
                ('akuma', models.IntegerField()),
                ('mbison', models.IntegerField()),
                ('terry', models.IntegerField()),
                ('mai', models.IntegerField()),
                ('elena', models.IntegerField()),
            ],
        ),
    ]
