# Generated by Django 5.2.4 on 2025-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_alter_diagram_aki_alter_diagram_akuma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
