# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_alter_characters_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
